- name: Remove docker repo if exists
  file:
    path: /etc/yum.repos.d/docker-ce.repo
    state: absent

- name: Add CRI-O repo
  copy:
    dest: /etc/yum.repos.d/crio.repo
    content: |
      [cri-o]
      name=CRI-O
      baseurl=https://download.opensuse.org/repositories/isv:/cri-o:/stable:/v1.33/rpm/
      enabled=1
      gpgcheck=0

- name: Install CRI-O
  dnf:
    name: cri-o
    state: present

- name: Enable and start CRI-O
  service:
    name: crio
    state: started
    enabled: yes

- name: Disable swap
  command: swapoff -a