- name: Add Kubernetes repo
  copy:
    dest: /etc/yum.repos.d/kubernetes.repo
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://pkgs.k8s.io/core:/stable:/v1.33/rpm/
      enabled=1
      gpgcheck=1
      gpgkey=https://pkgs.k8s.io/core:/stable:/v1.33/rpm/repodata/repomd.xml.key

- name: Install Kubernetes packages
  dnf:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Enable kubelet
  service:
    name: kubelet
    enabled: yes
    state: started