- name: Deploy Application
  hosts: master
  become: yes

  environment:
     KUBECONFIG: /etc/kubernetes/admin.conf
     PATH: "/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin"

  tasks:

    - name: Apply Kubernetes manifests
      command: kubectl apply -f {{ item }}
      loop:
        - ../k8s-manifests/deployment.yaml
        - ../k8s-manifests/service.yaml
        - ../k8s-manifests/ingress.yaml