- name: Deploy Application
  hosts: master
  become: yes

  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
    PATH: "/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin"

  tasks:

    - name: Copy project01.yaml manifest
      copy:
        src: ../argocd/project01.yaml
        dest: /tmp/project01.yaml

    - name: Apply project01.yaml
      command: kubectl apply -f /tmp/project01.yaml

    - name: Copy project02.yaml manifest
      copy:
        src: ../argocd/project02.yaml
        dest: /tmp/project02.yaml

    - name: Apply project02.yaml
      command: kubectl apply -f /tmp/project02.yaml
    
    - name: Copy project002.yaml manifest
      copy:
        src: ../argocd/project002.yaml
        dest: /tmp/project002.yaml

    - name: Apply project002.yaml
      command: kubectl apply -f /tmp/project002.yaml
