apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-project
  namespace: argocd

spec:
  project: my-project

  source:
    repoURL: https://github.com/adarshadshetty09/kubernetes.git
    targetRevision: kubernete_files
    path: apache

  destination:
    server: https://kubernetes.default.svc
    namespace: httpd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
    syncOptions:
      - CreateNamespace=true

  revisionHistoryLimit: 5