apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-test-prod
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/adarshadshetty09/kubernetes.git
    targetRevision: kubernete_files
    path: project01

  destination:
    server: https://kubernetes.default.svc
    namespace: production

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
    syncOptions:
      - CreateNamespace=true

  revisionHistoryLimit: 5