apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd

spec:
  project: my-project   

  source:
    repoURL: https://github.com/adarshadshetty09/kubernetes.git
    targetRevision: kubernete_files
    path: apache

  destination:
    server: https://kubernetes.default.svc
    namespace: httpd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
